export const CREATE_INFO = 'CREATE_INFO';
export const CREATE_EXPERIENCE = 'CREATE_EXPERIENCE';
export const CREATE_EDUCATION = 'CREATE_EDUCATION';
export const CREATE_SKILL = 'CREATE_SKILL';
export const CREATE_PROJECT = 'CREATE_PROJECT';

